name: LootDrops
version: '1.3'
main: net.vanillaplus.lootdrops.Main
softdepend:
  - DiscordSRV
api-version: 1.17
commands:
  lootdrop:
    usage: /<command>
    permission: lootdrop.drop

  multidrop:
    usage: /<command>
    permission: lootdrop.multidrop

  delayeddrop:
    usage: /<command>
    permission: lootdrop.delayeddrop